export type LookupDto = {
  id: number;
  lookupName: string;
  code: string;
  displayValueEn: string;
  displayValueFr: string;
  effectiveDate: string;
};

export const lookupSeed: LookupDto[] = [
  {
    id: 1,
    lookupName: "Customer status",
    code: "CUSTOMER_STATUS_ACTIVE",
    displayValueEn: "Active",
    displayValueFr: "Actif",
    effectiveDate: "2026-01-01",
  },
  {
    id: 2,
    lookupName: "Customer status",
    code: "CUSTOMER_STATUS_PENDING",
    displayValueEn: "Pending review",
    displayValueFr: "En attente de revision",
    effectiveDate: "2026-01-01",
  },
  {
    id: 3,
    lookupName: "Customer status",
    code: "CUSTOMER_STATUS_INACTIVE",
    displayValueEn: "Inactive",
    displayValueFr: "Inactif",
    effectiveDate: "2026-01-01",
  },
  {
    id: 4,
    lookupName: "Region",
    code: "REGION_NORTH_AMERICA",
    displayValueEn: "North America",
    displayValueFr: "Amerique du Nord",
    effectiveDate: "2026-02-15",
  },
  {
    id: 5,
    lookupName: "Region",
    code: "REGION_EUROPE",
    displayValueEn: "Europe",
    displayValueFr: "Europe",
    effectiveDate: "2026-02-15",
  },
  {
    id: 6,
    lookupName: "Region",
    code: "REGION_APAC",
    displayValueEn: "Asia Pacific",
    displayValueFr: "Asie-Pacifique",
    effectiveDate: "2026-02-15",
  },
  {
    id: 7,
    lookupName: "Priority",
    code: "PRIORITY_HIGH",
    displayValueEn: "High",
    displayValueFr: "Elevee",
    effectiveDate: "2026-03-01",
  },
  {
    id: 8,
    lookupName: "Priority",
    code: "PRIORITY_MEDIUM",
    displayValueEn: "Medium",
    displayValueFr: "Moyenne",
    effectiveDate: "2026-03-01",
  },
  {
    id: 9,
    lookupName: "Priority",
    code: "PRIORITY_LOW",
    displayValueEn: "Low",
    displayValueFr: "Faible",
    effectiveDate: "2026-03-01",
  },
  {
    id: 10,
    lookupName: "Language",
    code: "LANGUAGE_EN",
    displayValueEn: "English",
    displayValueFr: "Anglais",
    effectiveDate: "2026-04-01",
  },
  {
    id: 11,
    lookupName: "Language",
    code: "LANGUAGE_FR",
    displayValueEn: "French",
    displayValueFr: "Francais",
    effectiveDate: "2026-04-01",
  },
  {
    id: 12,
    lookupName: "Contact method",
    code: "CONTACT_METHOD_EMAIL",
    displayValueEn: "Email",
    displayValueFr: "Courriel",
    effectiveDate: "2026-05-01",
  },
  {
    id: 13,
    lookupName: "Contact method",
    code: "CONTACT_METHOD_PHONE",
    displayValueEn: "Phone",
    displayValueFr: "Telephone",
    effectiveDate: "2026-05-01",
  },
  {
    id: 14,
    lookupName: "Contact method",
    code: "CONTACT_METHOD_SMS",
    displayValueEn: "Text message",
    displayValueFr: "Message texte",
    effectiveDate: "2026-05-01",
  },
  {
    id: 15,
    lookupName: "Billing cycle",
    code: "BILLING_CYCLE_MONTHLY",
    displayValueEn: "Monthly",
    displayValueFr: "Mensuel",
    effectiveDate: "2026-06-01",
  },
  {
    id: 16,
    lookupName: "Billing cycle",
    code: "BILLING_CYCLE_ANNUAL",
    displayValueEn: "Annual",
    displayValueFr: "Annuel",
    effectiveDate: "2026-06-01",
  },
  {
    id: 17,
    lookupName: "Account tier",
    code: "ACCOUNT_TIER_STANDARD",
    displayValueEn: "Standard",
    displayValueFr: "Standard",
    effectiveDate: "2026-06-15",
  },
  {
    id: 18,
    lookupName: "Account tier",
    code: "ACCOUNT_TIER_ENTERPRISE",
    displayValueEn: "Enterprise",
    displayValueFr: "Entreprise",
    effectiveDate: "2026-06-15",
  },
  {
    id: 19,
    lookupName: "Age",
    code: "AGE_18_24",
    displayValueEn: "18 to 24",
    displayValueFr: "18 a 24",
    effectiveDate: "2026-01-01",
  },
  {
    id: 20,
    lookupName: "Age",
    code: "AGE_25_34",
    displayValueEn: "25 to 34",
    displayValueFr: "25 a 34",
    effectiveDate: "2026-01-01",
  },
  {
    id: 21,
    lookupName: "Age",
    code: "AGE_35_44",
    displayValueEn: "35 to 44",
    displayValueFr: "35 a 44",
    effectiveDate: "2026-01-01",
  },
  {
    id: 22,
    lookupName: "Age",
    code: "AGE_45_54",
    displayValueEn: "45 to 54",
    displayValueFr: "45 a 54",
    effectiveDate: "2026-01-01",
  },
  {
    id: 23,
    lookupName: "Age",
    code: "AGE_55_PLUS",
    displayValueEn: "55 plus",
    displayValueFr: "55 et plus",
    effectiveDate: "2026-01-01",
  },
];
