/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTasksRouteRouteImport } from './routes/api/tasks/route'
import { Route as ApiNotesRouteRouteImport } from './routes/api/notes/route'
import { Route as ApiLookupsRouteRouteImport } from './routes/api/lookups/route'
import { Route as ApiGroupsRouteRouteImport } from './routes/api/groups/route'
import { Route as ApiCustomersRouteRouteImport } from './routes/api/customers/route'
import { Route as AppVinRouteRouteImport } from './routes/_app/vin/route'
import { Route as AppTasksRouteRouteImport } from './routes/_app/tasks/route'
import { Route as AppNotesRouteRouteImport } from './routes/_app/notes/route'
import { Route as AppLookupsRouteRouteImport } from './routes/_app/lookups/route'
import { Route as AppLoadRouteRouteImport } from './routes/_app/load/route'
import { Route as AppKrakenRouteRouteImport } from './routes/_app/kraken/route'
import { Route as AppGroupsRouteRouteImport } from './routes/_app/groups/route'
import { Route as AppDrivingLicenceRouteRouteImport } from './routes/_app/driving-licence/route'
import { Route as AppCustomersRouteRouteImport } from './routes/_app/customers/route'
import { Route as AppLookupsIndexRouteImport } from './routes/_app/lookups/index'
import { Route as AppKrakenIndexRouteImport } from './routes/_app/kraken/index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as ApiVinWmisRouteImport } from './routes/api/vin/wmis'
import { Route as ApiVinModelsRouteImport } from './routes/api/vin/models'
import { Route as ApiVinBrandsRouteImport } from './routes/api/vin/brands'
import { Route as ApiQuotesBusinessKeyRouteImport } from './routes/api/quotes/$businessKey'
import { Route as ApiPoliciesBusinessKeyRouteImport } from './routes/api/policies/$businessKey'
import { Route as ApiCustomersCustomerIdRouteImport } from './routes/api/customers/$customerId'
import { Route as AppPoliciesBusinessKeyRouteImport } from './routes/_app/policies/$businessKey'
import { Route as AppLookupsLookupNameRouteImport } from './routes/_app/lookups/$lookupName'
import { Route as AppKrakenEntrypointNameRouteImport } from './routes/_app/kraken/$entrypointName'
import { Route as AppCustomersFavoritesRouteImport } from './routes/_app/customers/favorites'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app/customers/$customerId'
import { Route as ApiLookupsNamesRouteRouteImport } from './routes/api/lookups/names/route'
import { Route as ApiKrakenEntrypointsRouteRouteImport } from './routes/api/kraken/entrypoints/route'
import { Route as ApiLookupsNamesLookupNameRouteImport } from './routes/api/lookups/names/$lookupName'
import { Route as AppQuotesBusinessKeyRevisionNumberRouteImport } from './routes/_app/quotes/$businessKey/$revisionNumber'
import { Route as ApiKrakenEntrypointsEntrypointNameRulesRouteImport } from './routes/api/kraken/entrypoints/$entrypointName/rules'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRouteRoute = ApiTasksRouteRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesRouteRoute = ApiNotesRouteRouteImport.update({
  id: '/api/notes',
  path: '/api/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLookupsRouteRoute = ApiLookupsRouteRouteImport.update({
  id: '/api/lookups',
  path: '/api/lookups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroupsRouteRoute = ApiGroupsRouteRouteImport.update({
  id: '/api/groups',
  path: '/api/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomersRouteRoute = ApiCustomersRouteRouteImport.update({
  id: '/api/customers',
  path: '/api/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVinRouteRoute = AppVinRouteRouteImport.update({
  id: '/vin',
  path: '/vin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTasksRouteRoute = AppTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesRouteRoute = AppNotesRouteRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLookupsRouteRoute = AppLookupsRouteRouteImport.update({
  id: '/lookups',
  path: '/lookups',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoadRouteRoute = AppLoadRouteRouteImport.update({
  id: '/load',
  path: '/load',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKrakenRouteRoute = AppKrakenRouteRouteImport.update({
  id: '/kraken',
  path: '/kraken',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGroupsRouteRoute = AppGroupsRouteRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDrivingLicenceRouteRoute = AppDrivingLicenceRouteRouteImport.update({
  id: '/driving-licence',
  path: '/driving-licence',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersRouteRoute = AppCustomersRouteRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLookupsIndexRoute = AppLookupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLookupsRouteRoute,
} as any)
const AppKrakenIndexRoute = AppKrakenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppKrakenRouteRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCustomersRouteRoute,
} as any)
const ApiVinWmisRoute = ApiVinWmisRouteImport.update({
  id: '/api/vin/wmis',
  path: '/api/vin/wmis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVinModelsRoute = ApiVinModelsRouteImport.update({
  id: '/api/vin/models',
  path: '/api/vin/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVinBrandsRoute = ApiVinBrandsRouteImport.update({
  id: '/api/vin/brands',
  path: '/api/vin/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesBusinessKeyRoute = ApiQuotesBusinessKeyRouteImport.update({
  id: '/api/quotes/$businessKey',
  path: '/api/quotes/$businessKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPoliciesBusinessKeyRoute = ApiPoliciesBusinessKeyRouteImport.update({
  id: '/api/policies/$businessKey',
  path: '/api/policies/$businessKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomersCustomerIdRoute = ApiCustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => ApiCustomersRouteRoute,
} as any)
const AppPoliciesBusinessKeyRoute = AppPoliciesBusinessKeyRouteImport.update({
  id: '/policies/$businessKey',
  path: '/policies/$businessKey',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLookupsLookupNameRoute = AppLookupsLookupNameRouteImport.update({
  id: '/$lookupName',
  path: '/$lookupName',
  getParentRoute: () => AppLookupsRouteRoute,
} as any)
const AppKrakenEntrypointNameRoute = AppKrakenEntrypointNameRouteImport.update({
  id: '/$entrypointName',
  path: '/$entrypointName',
  getParentRoute: () => AppKrakenRouteRoute,
} as any)
const AppCustomersFavoritesRoute = AppCustomersFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppCustomersRouteRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => AppCustomersRouteRoute,
} as any)
const ApiLookupsNamesRouteRoute = ApiLookupsNamesRouteRouteImport.update({
  id: '/names',
  path: '/names',
  getParentRoute: () => ApiLookupsRouteRoute,
} as any)
const ApiKrakenEntrypointsRouteRoute =
  ApiKrakenEntrypointsRouteRouteImport.update({
    id: '/api/kraken/entrypoints',
    path: '/api/kraken/entrypoints',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLookupsNamesLookupNameRoute =
  ApiLookupsNamesLookupNameRouteImport.update({
    id: '/$lookupName',
    path: '/$lookupName',
    getParentRoute: () => ApiLookupsNamesRouteRoute,
  } as any)
const AppQuotesBusinessKeyRevisionNumberRoute =
  AppQuotesBusinessKeyRevisionNumberRouteImport.update({
    id: '/quotes/$businessKey/$revisionNumber',
    path: '/quotes/$businessKey/$revisionNumber',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApiKrakenEntrypointsEntrypointNameRulesRoute =
  ApiKrakenEntrypointsEntrypointNameRulesRouteImport.update({
    id: '/$entrypointName/rules',
    path: '/$entrypointName/rules',
    getParentRoute: () => ApiKrakenEntrypointsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof AppCustomersRouteRouteWithChildren
  '/driving-licence': typeof AppDrivingLicenceRouteRoute
  '/groups': typeof AppGroupsRouteRoute
  '/kraken': typeof AppKrakenRouteRouteWithChildren
  '/load': typeof AppLoadRouteRoute
  '/lookups': typeof AppLookupsRouteRouteWithChildren
  '/notes': typeof AppNotesRouteRoute
  '/tasks': typeof AppTasksRouteRoute
  '/vin': typeof AppVinRouteRoute
  '/api/customers': typeof ApiCustomersRouteRouteWithChildren
  '/api/groups': typeof ApiGroupsRouteRoute
  '/api/lookups': typeof ApiLookupsRouteRouteWithChildren
  '/api/notes': typeof ApiNotesRouteRoute
  '/api/tasks': typeof ApiTasksRouteRoute
  '/api/kraken/entrypoints': typeof ApiKrakenEntrypointsRouteRouteWithChildren
  '/api/lookups/names': typeof ApiLookupsNamesRouteRouteWithChildren
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/customers/favorites': typeof AppCustomersFavoritesRoute
  '/kraken/$entrypointName': typeof AppKrakenEntrypointNameRoute
  '/lookups/$lookupName': typeof AppLookupsLookupNameRoute
  '/policies/$businessKey': typeof AppPoliciesBusinessKeyRoute
  '/api/customers/$customerId': typeof ApiCustomersCustomerIdRoute
  '/api/policies/$businessKey': typeof ApiPoliciesBusinessKeyRoute
  '/api/quotes/$businessKey': typeof ApiQuotesBusinessKeyRoute
  '/api/vin/brands': typeof ApiVinBrandsRoute
  '/api/vin/models': typeof ApiVinModelsRoute
  '/api/vin/wmis': typeof ApiVinWmisRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/kraken/': typeof AppKrakenIndexRoute
  '/lookups/': typeof AppLookupsIndexRoute
  '/quotes/$businessKey/$revisionNumber': typeof AppQuotesBusinessKeyRevisionNumberRoute
  '/api/lookups/names/$lookupName': typeof ApiLookupsNamesLookupNameRoute
  '/api/kraken/entrypoints/$entrypointName/rules': typeof ApiKrakenEntrypointsEntrypointNameRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/driving-licence': typeof AppDrivingLicenceRouteRoute
  '/groups': typeof AppGroupsRouteRoute
  '/load': typeof AppLoadRouteRoute
  '/notes': typeof AppNotesRouteRoute
  '/tasks': typeof AppTasksRouteRoute
  '/vin': typeof AppVinRouteRoute
  '/api/customers': typeof ApiCustomersRouteRouteWithChildren
  '/api/groups': typeof ApiGroupsRouteRoute
  '/api/lookups': typeof ApiLookupsRouteRouteWithChildren
  '/api/notes': typeof ApiNotesRouteRoute
  '/api/tasks': typeof ApiTasksRouteRoute
  '/api/kraken/entrypoints': typeof ApiKrakenEntrypointsRouteRouteWithChildren
  '/api/lookups/names': typeof ApiLookupsNamesRouteRouteWithChildren
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/customers/favorites': typeof AppCustomersFavoritesRoute
  '/kraken/$entrypointName': typeof AppKrakenEntrypointNameRoute
  '/lookups/$lookupName': typeof AppLookupsLookupNameRoute
  '/policies/$businessKey': typeof AppPoliciesBusinessKeyRoute
  '/api/customers/$customerId': typeof ApiCustomersCustomerIdRoute
  '/api/policies/$businessKey': typeof ApiPoliciesBusinessKeyRoute
  '/api/quotes/$businessKey': typeof ApiQuotesBusinessKeyRoute
  '/api/vin/brands': typeof ApiVinBrandsRoute
  '/api/vin/models': typeof ApiVinModelsRoute
  '/api/vin/wmis': typeof ApiVinWmisRoute
  '/customers': typeof AppCustomersIndexRoute
  '/kraken': typeof AppKrakenIndexRoute
  '/lookups': typeof AppLookupsIndexRoute
  '/quotes/$businessKey/$revisionNumber': typeof AppQuotesBusinessKeyRevisionNumberRoute
  '/api/lookups/names/$lookupName': typeof ApiLookupsNamesLookupNameRoute
  '/api/kraken/entrypoints/$entrypointName/rules': typeof ApiKrakenEntrypointsEntrypointNameRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/customers': typeof AppCustomersRouteRouteWithChildren
  '/_app/driving-licence': typeof AppDrivingLicenceRouteRoute
  '/_app/groups': typeof AppGroupsRouteRoute
  '/_app/kraken': typeof AppKrakenRouteRouteWithChildren
  '/_app/load': typeof AppLoadRouteRoute
  '/_app/lookups': typeof AppLookupsRouteRouteWithChildren
  '/_app/notes': typeof AppNotesRouteRoute
  '/_app/tasks': typeof AppTasksRouteRoute
  '/_app/vin': typeof AppVinRouteRoute
  '/api/customers': typeof ApiCustomersRouteRouteWithChildren
  '/api/groups': typeof ApiGroupsRouteRoute
  '/api/lookups': typeof ApiLookupsRouteRouteWithChildren
  '/api/notes': typeof ApiNotesRouteRoute
  '/api/tasks': typeof ApiTasksRouteRoute
  '/api/kraken/entrypoints': typeof ApiKrakenEntrypointsRouteRouteWithChildren
  '/api/lookups/names': typeof ApiLookupsNamesRouteRouteWithChildren
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/customers/favorites': typeof AppCustomersFavoritesRoute
  '/_app/kraken/$entrypointName': typeof AppKrakenEntrypointNameRoute
  '/_app/lookups/$lookupName': typeof AppLookupsLookupNameRoute
  '/_app/policies/$businessKey': typeof AppPoliciesBusinessKeyRoute
  '/api/customers/$customerId': typeof ApiCustomersCustomerIdRoute
  '/api/policies/$businessKey': typeof ApiPoliciesBusinessKeyRoute
  '/api/quotes/$businessKey': typeof ApiQuotesBusinessKeyRoute
  '/api/vin/brands': typeof ApiVinBrandsRoute
  '/api/vin/models': typeof ApiVinModelsRoute
  '/api/vin/wmis': typeof ApiVinWmisRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/kraken/': typeof AppKrakenIndexRoute
  '/_app/lookups/': typeof AppLookupsIndexRoute
  '/_app/quotes/$businessKey/$revisionNumber': typeof AppQuotesBusinessKeyRevisionNumberRoute
  '/api/lookups/names/$lookupName': typeof ApiLookupsNamesLookupNameRoute
  '/api/kraken/entrypoints/$entrypointName/rules': typeof ApiKrakenEntrypointsEntrypointNameRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/driving-licence'
    | '/groups'
    | '/kraken'
    | '/load'
    | '/lookups'
    | '/notes'
    | '/tasks'
    | '/vin'
    | '/api/customers'
    | '/api/groups'
    | '/api/lookups'
    | '/api/notes'
    | '/api/tasks'
    | '/api/kraken/entrypoints'
    | '/api/lookups/names'
    | '/customers/$customerId'
    | '/customers/favorites'
    | '/kraken/$entrypointName'
    | '/lookups/$lookupName'
    | '/policies/$businessKey'
    | '/api/customers/$customerId'
    | '/api/policies/$businessKey'
    | '/api/quotes/$businessKey'
    | '/api/vin/brands'
    | '/api/vin/models'
    | '/api/vin/wmis'
    | '/customers/'
    | '/kraken/'
    | '/lookups/'
    | '/quotes/$businessKey/$revisionNumber'
    | '/api/lookups/names/$lookupName'
    | '/api/kraken/entrypoints/$entrypointName/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/driving-licence'
    | '/groups'
    | '/load'
    | '/notes'
    | '/tasks'
    | '/vin'
    | '/api/customers'
    | '/api/groups'
    | '/api/lookups'
    | '/api/notes'
    | '/api/tasks'
    | '/api/kraken/entrypoints'
    | '/api/lookups/names'
    | '/customers/$customerId'
    | '/customers/favorites'
    | '/kraken/$entrypointName'
    | '/lookups/$lookupName'
    | '/policies/$businessKey'
    | '/api/customers/$customerId'
    | '/api/policies/$businessKey'
    | '/api/quotes/$businessKey'
    | '/api/vin/brands'
    | '/api/vin/models'
    | '/api/vin/wmis'
    | '/customers'
    | '/kraken'
    | '/lookups'
    | '/quotes/$businessKey/$revisionNumber'
    | '/api/lookups/names/$lookupName'
    | '/api/kraken/entrypoints/$entrypointName/rules'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/customers'
    | '/_app/driving-licence'
    | '/_app/groups'
    | '/_app/kraken'
    | '/_app/load'
    | '/_app/lookups'
    | '/_app/notes'
    | '/_app/tasks'
    | '/_app/vin'
    | '/api/customers'
    | '/api/groups'
    | '/api/lookups'
    | '/api/notes'
    | '/api/tasks'
    | '/api/kraken/entrypoints'
    | '/api/lookups/names'
    | '/_app/customers/$customerId'
    | '/_app/customers/favorites'
    | '/_app/kraken/$entrypointName'
    | '/_app/lookups/$lookupName'
    | '/_app/policies/$businessKey'
    | '/api/customers/$customerId'
    | '/api/policies/$businessKey'
    | '/api/quotes/$businessKey'
    | '/api/vin/brands'
    | '/api/vin/models'
    | '/api/vin/wmis'
    | '/_app/customers/'
    | '/_app/kraken/'
    | '/_app/lookups/'
    | '/_app/quotes/$businessKey/$revisionNumber'
    | '/api/lookups/names/$lookupName'
    | '/api/kraken/entrypoints/$entrypointName/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiCustomersRouteRoute: typeof ApiCustomersRouteRouteWithChildren
  ApiGroupsRouteRoute: typeof ApiGroupsRouteRoute
  ApiLookupsRouteRoute: typeof ApiLookupsRouteRouteWithChildren
  ApiNotesRouteRoute: typeof ApiNotesRouteRoute
  ApiTasksRouteRoute: typeof ApiTasksRouteRoute
  ApiKrakenEntrypointsRouteRoute: typeof ApiKrakenEntrypointsRouteRouteWithChildren
  ApiPoliciesBusinessKeyRoute: typeof ApiPoliciesBusinessKeyRoute
  ApiQuotesBusinessKeyRoute: typeof ApiQuotesBusinessKeyRoute
  ApiVinBrandsRoute: typeof ApiVinBrandsRoute
  ApiVinModelsRoute: typeof ApiVinModelsRoute
  ApiVinWmisRoute: typeof ApiVinWmisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes': {
      id: '/api/notes'
      path: '/api/notes'
      fullPath: '/api/notes'
      preLoaderRoute: typeof ApiNotesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lookups': {
      id: '/api/lookups'
      path: '/api/lookups'
      fullPath: '/api/lookups'
      preLoaderRoute: typeof ApiLookupsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groups': {
      id: '/api/groups'
      path: '/api/groups'
      fullPath: '/api/groups'
      preLoaderRoute: typeof ApiGroupsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customers': {
      id: '/api/customers'
      path: '/api/customers'
      fullPath: '/api/customers'
      preLoaderRoute: typeof ApiCustomersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vin': {
      id: '/_app/vin'
      path: '/vin'
      fullPath: '/vin'
      preLoaderRoute: typeof AppVinRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lookups': {
      id: '/_app/lookups'
      path: '/lookups'
      fullPath: '/lookups'
      preLoaderRoute: typeof AppLookupsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/load': {
      id: '/_app/load'
      path: '/load'
      fullPath: '/load'
      preLoaderRoute: typeof AppLoadRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/kraken': {
      id: '/_app/kraken'
      path: '/kraken'
      fullPath: '/kraken'
      preLoaderRoute: typeof AppKrakenRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/driving-licence': {
      id: '/_app/driving-licence'
      path: '/driving-licence'
      fullPath: '/driving-licence'
      preLoaderRoute: typeof AppDrivingLicenceRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lookups/': {
      id: '/_app/lookups/'
      path: '/'
      fullPath: '/lookups/'
      preLoaderRoute: typeof AppLookupsIndexRouteImport
      parentRoute: typeof AppLookupsRouteRoute
    }
    '/_app/kraken/': {
      id: '/_app/kraken/'
      path: '/'
      fullPath: '/kraken/'
      preLoaderRoute: typeof AppKrakenIndexRouteImport
      parentRoute: typeof AppKrakenRouteRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppCustomersRouteRoute
    }
    '/api/vin/wmis': {
      id: '/api/vin/wmis'
      path: '/api/vin/wmis'
      fullPath: '/api/vin/wmis'
      preLoaderRoute: typeof ApiVinWmisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vin/models': {
      id: '/api/vin/models'
      path: '/api/vin/models'
      fullPath: '/api/vin/models'
      preLoaderRoute: typeof ApiVinModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vin/brands': {
      id: '/api/vin/brands'
      path: '/api/vin/brands'
      fullPath: '/api/vin/brands'
      preLoaderRoute: typeof ApiVinBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes/$businessKey': {
      id: '/api/quotes/$businessKey'
      path: '/api/quotes/$businessKey'
      fullPath: '/api/quotes/$businessKey'
      preLoaderRoute: typeof ApiQuotesBusinessKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/policies/$businessKey': {
      id: '/api/policies/$businessKey'
      path: '/api/policies/$businessKey'
      fullPath: '/api/policies/$businessKey'
      preLoaderRoute: typeof ApiPoliciesBusinessKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customers/$customerId': {
      id: '/api/customers/$customerId'
      path: '/$customerId'
      fullPath: '/api/customers/$customerId'
      preLoaderRoute: typeof ApiCustomersCustomerIdRouteImport
      parentRoute: typeof ApiCustomersRouteRoute
    }
    '/_app/policies/$businessKey': {
      id: '/_app/policies/$businessKey'
      path: '/policies/$businessKey'
      fullPath: '/policies/$businessKey'
      preLoaderRoute: typeof AppPoliciesBusinessKeyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lookups/$lookupName': {
      id: '/_app/lookups/$lookupName'
      path: '/$lookupName'
      fullPath: '/lookups/$lookupName'
      preLoaderRoute: typeof AppLookupsLookupNameRouteImport
      parentRoute: typeof AppLookupsRouteRoute
    }
    '/_app/kraken/$entrypointName': {
      id: '/_app/kraken/$entrypointName'
      path: '/$entrypointName'
      fullPath: '/kraken/$entrypointName'
      preLoaderRoute: typeof AppKrakenEntrypointNameRouteImport
      parentRoute: typeof AppKrakenRouteRoute
    }
    '/_app/customers/favorites': {
      id: '/_app/customers/favorites'
      path: '/favorites'
      fullPath: '/customers/favorites'
      preLoaderRoute: typeof AppCustomersFavoritesRouteImport
      parentRoute: typeof AppCustomersRouteRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppCustomersRouteRoute
    }
    '/api/lookups/names': {
      id: '/api/lookups/names'
      path: '/names'
      fullPath: '/api/lookups/names'
      preLoaderRoute: typeof ApiLookupsNamesRouteRouteImport
      parentRoute: typeof ApiLookupsRouteRoute
    }
    '/api/kraken/entrypoints': {
      id: '/api/kraken/entrypoints'
      path: '/api/kraken/entrypoints'
      fullPath: '/api/kraken/entrypoints'
      preLoaderRoute: typeof ApiKrakenEntrypointsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lookups/names/$lookupName': {
      id: '/api/lookups/names/$lookupName'
      path: '/$lookupName'
      fullPath: '/api/lookups/names/$lookupName'
      preLoaderRoute: typeof ApiLookupsNamesLookupNameRouteImport
      parentRoute: typeof ApiLookupsNamesRouteRoute
    }
    '/_app/quotes/$businessKey/$revisionNumber': {
      id: '/_app/quotes/$businessKey/$revisionNumber'
      path: '/quotes/$businessKey/$revisionNumber'
      fullPath: '/quotes/$businessKey/$revisionNumber'
      preLoaderRoute: typeof AppQuotesBusinessKeyRevisionNumberRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/kraken/entrypoints/$entrypointName/rules': {
      id: '/api/kraken/entrypoints/$entrypointName/rules'
      path: '/$entrypointName/rules'
      fullPath: '/api/kraken/entrypoints/$entrypointName/rules'
      preLoaderRoute: typeof ApiKrakenEntrypointsEntrypointNameRulesRouteImport
      parentRoute: typeof ApiKrakenEntrypointsRouteRoute
    }
  }
}

interface AppCustomersRouteRouteChildren {
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppCustomersFavoritesRoute: typeof AppCustomersFavoritesRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
}

const AppCustomersRouteRouteChildren: AppCustomersRouteRouteChildren = {
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppCustomersFavoritesRoute: AppCustomersFavoritesRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
}

const AppCustomersRouteRouteWithChildren =
  AppCustomersRouteRoute._addFileChildren(AppCustomersRouteRouteChildren)

interface AppKrakenRouteRouteChildren {
  AppKrakenEntrypointNameRoute: typeof AppKrakenEntrypointNameRoute
  AppKrakenIndexRoute: typeof AppKrakenIndexRoute
}

const AppKrakenRouteRouteChildren: AppKrakenRouteRouteChildren = {
  AppKrakenEntrypointNameRoute: AppKrakenEntrypointNameRoute,
  AppKrakenIndexRoute: AppKrakenIndexRoute,
}

const AppKrakenRouteRouteWithChildren = AppKrakenRouteRoute._addFileChildren(
  AppKrakenRouteRouteChildren,
)

interface AppLookupsRouteRouteChildren {
  AppLookupsLookupNameRoute: typeof AppLookupsLookupNameRoute
  AppLookupsIndexRoute: typeof AppLookupsIndexRoute
}

const AppLookupsRouteRouteChildren: AppLookupsRouteRouteChildren = {
  AppLookupsLookupNameRoute: AppLookupsLookupNameRoute,
  AppLookupsIndexRoute: AppLookupsIndexRoute,
}

const AppLookupsRouteRouteWithChildren = AppLookupsRouteRoute._addFileChildren(
  AppLookupsRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppCustomersRouteRoute: typeof AppCustomersRouteRouteWithChildren
  AppDrivingLicenceRouteRoute: typeof AppDrivingLicenceRouteRoute
  AppGroupsRouteRoute: typeof AppGroupsRouteRoute
  AppKrakenRouteRoute: typeof AppKrakenRouteRouteWithChildren
  AppLoadRouteRoute: typeof AppLoadRouteRoute
  AppLookupsRouteRoute: typeof AppLookupsRouteRouteWithChildren
  AppNotesRouteRoute: typeof AppNotesRouteRoute
  AppTasksRouteRoute: typeof AppTasksRouteRoute
  AppVinRouteRoute: typeof AppVinRouteRoute
  AppPoliciesBusinessKeyRoute: typeof AppPoliciesBusinessKeyRoute
  AppQuotesBusinessKeyRevisionNumberRoute: typeof AppQuotesBusinessKeyRevisionNumberRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCustomersRouteRoute: AppCustomersRouteRouteWithChildren,
  AppDrivingLicenceRouteRoute: AppDrivingLicenceRouteRoute,
  AppGroupsRouteRoute: AppGroupsRouteRoute,
  AppKrakenRouteRoute: AppKrakenRouteRouteWithChildren,
  AppLoadRouteRoute: AppLoadRouteRoute,
  AppLookupsRouteRoute: AppLookupsRouteRouteWithChildren,
  AppNotesRouteRoute: AppNotesRouteRoute,
  AppTasksRouteRoute: AppTasksRouteRoute,
  AppVinRouteRoute: AppVinRouteRoute,
  AppPoliciesBusinessKeyRoute: AppPoliciesBusinessKeyRoute,
  AppQuotesBusinessKeyRevisionNumberRoute:
    AppQuotesBusinessKeyRevisionNumberRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ApiCustomersRouteRouteChildren {
  ApiCustomersCustomerIdRoute: typeof ApiCustomersCustomerIdRoute
}

const ApiCustomersRouteRouteChildren: ApiCustomersRouteRouteChildren = {
  ApiCustomersCustomerIdRoute: ApiCustomersCustomerIdRoute,
}

const ApiCustomersRouteRouteWithChildren =
  ApiCustomersRouteRoute._addFileChildren(ApiCustomersRouteRouteChildren)

interface ApiLookupsNamesRouteRouteChildren {
  ApiLookupsNamesLookupNameRoute: typeof ApiLookupsNamesLookupNameRoute
}

const ApiLookupsNamesRouteRouteChildren: ApiLookupsNamesRouteRouteChildren = {
  ApiLookupsNamesLookupNameRoute: ApiLookupsNamesLookupNameRoute,
}

const ApiLookupsNamesRouteRouteWithChildren =
  ApiLookupsNamesRouteRoute._addFileChildren(ApiLookupsNamesRouteRouteChildren)

interface ApiLookupsRouteRouteChildren {
  ApiLookupsNamesRouteRoute: typeof ApiLookupsNamesRouteRouteWithChildren
}

const ApiLookupsRouteRouteChildren: ApiLookupsRouteRouteChildren = {
  ApiLookupsNamesRouteRoute: ApiLookupsNamesRouteRouteWithChildren,
}

const ApiLookupsRouteRouteWithChildren = ApiLookupsRouteRoute._addFileChildren(
  ApiLookupsRouteRouteChildren,
)

interface ApiKrakenEntrypointsRouteRouteChildren {
  ApiKrakenEntrypointsEntrypointNameRulesRoute: typeof ApiKrakenEntrypointsEntrypointNameRulesRoute
}

const ApiKrakenEntrypointsRouteRouteChildren: ApiKrakenEntrypointsRouteRouteChildren =
  {
    ApiKrakenEntrypointsEntrypointNameRulesRoute:
      ApiKrakenEntrypointsEntrypointNameRulesRoute,
  }

const ApiKrakenEntrypointsRouteRouteWithChildren =
  ApiKrakenEntrypointsRouteRoute._addFileChildren(
    ApiKrakenEntrypointsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiCustomersRouteRoute: ApiCustomersRouteRouteWithChildren,
  ApiGroupsRouteRoute: ApiGroupsRouteRoute,
  ApiLookupsRouteRoute: ApiLookupsRouteRouteWithChildren,
  ApiNotesRouteRoute: ApiNotesRouteRoute,
  ApiTasksRouteRoute: ApiTasksRouteRoute,
  ApiKrakenEntrypointsRouteRoute: ApiKrakenEntrypointsRouteRouteWithChildren,
  ApiPoliciesBusinessKeyRoute: ApiPoliciesBusinessKeyRoute,
  ApiQuotesBusinessKeyRoute: ApiQuotesBusinessKeyRoute,
  ApiVinBrandsRoute: ApiVinBrandsRoute,
  ApiVinModelsRoute: ApiVinModelsRoute,
  ApiVinWmisRoute: ApiVinWmisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
