/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPeopleRouteImport } from './routes/api/people'
import { Route as ApiCustomersRouteImport } from './routes/api/customers'
import { Route as ApiCompaniesRouteImport } from './routes/api/companies'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppPeopleRouteImport } from './routes/_app/people'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppKrakenRouteImport } from './routes/_app/kraken'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppCompaniesRouteImport } from './routes/_app/companies'
import { Route as ApiCustomersCustomerIdRouteImport } from './routes/api/customers.$customerId'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app/customers_.$customerId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeopleRoute = ApiPeopleRouteImport.update({
  id: '/api/people',
  path: '/api/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomersRoute = ApiCustomersRouteImport.update({
  id: '/api/customers',
  path: '/api/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompaniesRoute = ApiCompaniesRouteImport.update({
  id: '/api/companies',
  path: '/api/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppKrakenRoute = AppKrakenRouteImport.update({
  id: '/kraken',
  path: '/kraken',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const ApiCustomersCustomerIdRoute = ApiCustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => ApiCustomersRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers_/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof AppCompaniesRoute
  '/customers': typeof AppCustomersRoute
  '/kraken': typeof AppKrakenRoute
  '/notes': typeof AppNotesRoute
  '/people': typeof AppPeopleRoute
  '/tasks': typeof AppTasksRoute
  '/api/companies': typeof ApiCompaniesRoute
  '/api/customers': typeof ApiCustomersRouteWithChildren
  '/api/people': typeof ApiPeopleRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/api/customers/$customerId': typeof ApiCustomersCustomerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof AppCompaniesRoute
  '/customers': typeof AppCustomersRoute
  '/kraken': typeof AppKrakenRoute
  '/notes': typeof AppNotesRoute
  '/people': typeof AppPeopleRoute
  '/tasks': typeof AppTasksRoute
  '/api/companies': typeof ApiCompaniesRoute
  '/api/customers': typeof ApiCustomersRouteWithChildren
  '/api/people': typeof ApiPeopleRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/api/customers/$customerId': typeof ApiCustomersCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/companies': typeof AppCompaniesRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/kraken': typeof AppKrakenRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/people': typeof AppPeopleRoute
  '/_app/tasks': typeof AppTasksRoute
  '/api/companies': typeof ApiCompaniesRoute
  '/api/customers': typeof ApiCustomersRouteWithChildren
  '/api/people': typeof ApiPeopleRoute
  '/_app/customers_/$customerId': typeof AppCustomersCustomerIdRoute
  '/api/customers/$customerId': typeof ApiCustomersCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/customers'
    | '/kraken'
    | '/notes'
    | '/people'
    | '/tasks'
    | '/api/companies'
    | '/api/customers'
    | '/api/people'
    | '/customers/$customerId'
    | '/api/customers/$customerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies'
    | '/customers'
    | '/kraken'
    | '/notes'
    | '/people'
    | '/tasks'
    | '/api/companies'
    | '/api/customers'
    | '/api/people'
    | '/customers/$customerId'
    | '/api/customers/$customerId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/companies'
    | '/_app/customers'
    | '/_app/kraken'
    | '/_app/notes'
    | '/_app/people'
    | '/_app/tasks'
    | '/api/companies'
    | '/api/customers'
    | '/api/people'
    | '/_app/customers_/$customerId'
    | '/api/customers/$customerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiCompaniesRoute: typeof ApiCompaniesRoute
  ApiCustomersRoute: typeof ApiCustomersRouteWithChildren
  ApiPeopleRoute: typeof ApiPeopleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/people': {
      id: '/api/people'
      path: '/api/people'
      fullPath: '/api/people'
      preLoaderRoute: typeof ApiPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customers': {
      id: '/api/customers'
      path: '/api/customers'
      fullPath: '/api/customers'
      preLoaderRoute: typeof ApiCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companies': {
      id: '/api/companies'
      path: '/api/companies'
      fullPath: '/api/companies'
      preLoaderRoute: typeof ApiCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kraken': {
      id: '/_app/kraken'
      path: '/kraken'
      fullPath: '/kraken'
      preLoaderRoute: typeof AppKrakenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/customers/$customerId': {
      id: '/api/customers/$customerId'
      path: '/$customerId'
      fullPath: '/api/customers/$customerId'
      preLoaderRoute: typeof ApiCustomersCustomerIdRouteImport
      parentRoute: typeof ApiCustomersRoute
    }
    '/_app/customers_/$customerId': {
      id: '/_app/customers_/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppKrakenRoute: typeof AppKrakenRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppTasksRoute: typeof AppTasksRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompaniesRoute: AppCompaniesRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppKrakenRoute: AppKrakenRoute,
  AppNotesRoute: AppNotesRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppTasksRoute: AppTasksRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiCustomersRouteChildren {
  ApiCustomersCustomerIdRoute: typeof ApiCustomersCustomerIdRoute
}

const ApiCustomersRouteChildren: ApiCustomersRouteChildren = {
  ApiCustomersCustomerIdRoute: ApiCustomersCustomerIdRoute,
}

const ApiCustomersRouteWithChildren = ApiCustomersRoute._addFileChildren(
  ApiCustomersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiCompaniesRoute: ApiCompaniesRoute,
  ApiCustomersRoute: ApiCustomersRouteWithChildren,
  ApiPeopleRoute: ApiPeopleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
